name: multitable
description: An application for studying multiplication tables and other examples from mathematics
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_svg: ^1.0.0
  easy_localization: ^3.0.0
  flutter_native_splash: ^1.3.2
  shared_preferences: ^2.0.11
  ocarina: ^0.1.2
  flutter_launcher_icons: ^0.9.2
  bart: ^0.1.1
  flutter_lints: ^1.0.4
  flutter_switch: ^0.3.2 #https://pub.flutter-io.cn/packages/flutter_switch

# dev_dependencies:

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  flutter_test:
    sdk: flutter
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  # разрешение 1500*2346
  image: assets/splash.png
  color: "732984"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/sound/
    - assets/translations/
